vim.cmd.colorscheme("rose-pine")

require("rockcity")

print("---- NVIM Shortcuts -----")
print("yy - Copy whole line")
print("p - Paste line")
print("Ctrl-W - Delete word")
print("dd - Delete line")
print("3dd - Delete Next 3 Lines")
print("Vjjd - Highlight 3 Next Lines then Delete (k goes other direction")
print("= - Apply Indent?")
print("Type Line Number to go to it")
print("Visual block selection then c49 to cut(copy?) 49 lines")
print("")
print("----- NetRc Shortcuts ------")
print("% - Create File")
print("d - Create Directory")
print("D - Delete")
print("----- Space Shortcuts -----")
print("pv - Netrc Explorer")
print("a - Add to Harpoon")
print("u - Undo Explorer")
print("gs - Git Menu")
print("")
print("")
print("----- Control Shortcuts -----")
print("e - Harpoon Menu")
print("h, t, n, s - First, Second, etc.. Harpoon File")
print("Wh - Move to Other Window (ex: Undo Window)")
print("")
print("HAVE TO ESC Before Selecting File in Telescope")
